---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role edx_service
#
# Overview:
#
# This role performs the repetive tasks that most edX roles
# require in our default configuration.
#
# Example play:
#
# Rather than being included in the play, this role
# is included as a dependency by other roles in the meta/mail.yml
# file.  The including role should add the following
# depency definition.
#
# dependencies:
#   - { role: edx_service, edx_service_name: "hotg" }
#

# Generating an ssh key so service users can do a git
# clone over ssh for public repositories without any
# additional configuration
- name: create application user
  user: >
    name="{{ edx_service_name }}"
    home="{{ COMMON_APP_DIR }}/{{ edx_service_name }}"
    createhome=yes
    shell=/bin/false
    generate_ssh_key=yes

# Assumes that the home directory has been created above.
- name: create edx_service app and venv dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ edx_service_name }}"
    group="{{ common_web_group }}"
  with_items:
    - "{{ COMMON_APP_DIR }}/{{ edx_service_name }}/venvs"

- name: create edx_service data and staticfiles dir
  file: >
    path="{{ item }}"
    state=directory
    owner="{{ edx_service_name }}"
    group="{{ common_web_group }}"
  with_items:
    - "{{ COMMON_DATA_DIR }}/{{ edx_service_name }}/data"
    - "{{ COMMON_DATA_DIR }}/{{ edx_service_name }}/staticfiles"


- name: create edx_service log dir
  file: >
    path="{{ item }}"
    state=directory
    owner="syslog"
    group="syslog"
  with_items:
    - "{{ COMMON_LOG_DIR }}/{{ edx_service_name }}"

- name: write out app config file
  template: >
    src=config.yml.j2
    dest={{ COMMON_CFG_DIR  }}/{{ edx_service_name }}.yml
    mode=0644
  tags:
    - deploy
  when: edx_service_config is defined

# Replace dashes with underscores to support roles that use
# dashes (the role vars will contain underscores)
- name: install a bunch of system packages on which edx_service relies
  apt: pkg={{ item }} state=present
  with_items: "{{ edx_service_name.replace('-', '_') }}_debian_pkgs"
  when: ansible_distribution in common_debian_variants

- name: install a bunch of system packages on which edx_service relies
  yum: pkg={{ item }} state=present
  with_items: "{{ edx_service_name.replace('-', '_') }}_redhat_pkgs"
  when: ansible_distribution in common_redhat_variants


- name: check if git repo exists before pruning
  stat: path={{item.DEST}}/.git
  register: git_dir_exists
  with_items: edx_service_config.GIT

- name: git prune before checking out
  shell: cd {{ item.DEST }} && git remote prune origin
  sudo_user: "{{ edxapp_user }}"
  notify:
    - restart {{edx_service_name}}
  when: >
    (git_dir_exists.stat.exists) and 
    (git_dir_exists.stat.isdir is defined) and
    git_dir_exists.stat.isdir
  with_items: edx_service_config.GIT


- name: validate GIT.PROTOCOL
  fail: msg='GIT.PROTOCOL must be "https" or "git"'
  when: (item.PROTOCOL != https) and (item.PROTOCOL != git)
  with_items: edx_service_config.GIT

- name: checkout code
  git: >
    repo={{ "%s{{item.DOMAIN}}%s{{item.PATH}}/{{item.REPO}}" | format(*["https://", "/"] if item.PROTOCOL=="https" else *["git@", ":"]) }}
    dest={{ item.DEST }}  version={{ item.VERSION }}
    accept_hostkey=yes key_file={{ edx_notes_api_home }}/.ssh/id_rsa
  sudo_user: "{{ edx_role_name }}"
  register: "{{edx_service_name}}_code_checkout"
  with_items: edx_service_config.GIT


- name: get instance information
  action: ec2_facts
  #old syntax

- name: tag instance
  ec2_tag: resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }}
  args:
    tags:
      "version:{{edx_service_name}}" : "{{item.DOMAIN}}/{{item.PATH}}/{{item.REPO}} {{ {{edx_service_name}}_code_checkout.after |truncate(7,True,'')}}"
  when: "{{edx_service_name}}_code_checkout.after is defined"
  with_items: edx_service_config.GIT